// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUP0WpUuHYFVL1WJlH89_7PoBV02WIWWE',
    appId: '1:405087099056:web:1b2832eed3a7c05b744375',
    messagingSenderId: '405087099056',
    projectId: 'firebase-giris',
    authDomain: 'fir-giris-7f973.firebaseapp.com',
    storageBucket: 'firebase-giris.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2trxk5sYgtmX4FkvduNKpeMklyr3tfd8',
    appId: '1:405087099056:android:b4891b84633a086f744375',
    messagingSenderId: '405087099056',
    projectId: 'firebase-giris',
    storageBucket: 'firebase-giris.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdwnpQ2j5ymH-6h3F8Qb3TQIj4Y6OAgmE',
    appId: '1:405087099056:ios:d241bb3a3790121b744375',
    messagingSenderId: '405087099056',
    projectId: 'firebase-giris',
    storageBucket: 'firebase-giris.appspot.com',
    iosClientId: '405087099056-trt08la5d4dek2ao45sgc5ml785e2tk5.apps.googleusercontent.com',
    iosBundleId: 'com.dh.firebaseGiris',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdwnpQ2j5ymH-6h3F8Qb3TQIj4Y6OAgmE',
    appId: '1:405087099056:ios:d241bb3a3790121b744375',
    messagingSenderId: '405087099056',
    projectId: 'firebase-giris',
    storageBucket: 'firebase-giris.appspot.com',
    iosClientId: '405087099056-trt08la5d4dek2ao45sgc5ml785e2tk5.apps.googleusercontent.com',
    iosBundleId: 'com.dh.firebaseGiris',
  );
}
